fix(k8sapi-executor): Fix KillContainer impl
Problem:
The Kubernetes API rejects exec calls that won't have at least one open
standard stream. When the k8sapi executor invokes the KillContainer
method, it tries to do so with no stream open at all, resulting in an
error: "Failed to kill main container: unable to upgrade connection: you
must specify at least 1 of stdin, stdout, stderr".

Changes:
Request stderr instead of nothing in the KillContainer implementation
of the k8sapi executor.

Result:
The k8sapi executor can successfully send the kill command to pods.