chore(tests): fix lint failures
Every PR has been failing the `make lint` checked with the following
error since https://github.com/argoproj/argo-workflows/pull/12960 was merged:
```
 			assert.Equal(t, 1, len(status.Outputs.Parameters))
			^
Error: test/e2e/suspend_test.go:124:4: len: use assert.Len (testifylint)
			assert.Equal(t, 1, len(status.Inputs.Parameters))
			^
make: *** [Makefile:466: lint] Error 1
```

This is happening due to a conflict between that PR and
https://github.com/argoproj/argo-workflows/pull/13467. The latter PR was
merged on August 14th, but the latest CI run for the former
(https://github.com/argoproj/argo-workflows/actions/runs/9191558853/job/25278229097)
was on May 22nd.

Signed-off-by: Mason Malone <651224+MasonM@users.noreply.github.com>