move logic to `root.go` instead
- running [`cmd.SetGLogLevel`](https://github.com/argoproj/argo-workflows/blob/a47e46208cd0029ef2e35019207d0b1ee4f85ea4/util/cmd/glog.go#L13) in `server.go` would cause a panic due to a flag redefinition of `klog`
  - i.e. `SetGLogLevel` can't be called twice
  - but `cli.SetLogLevel` worked fine

- also trying `command.Parent().PersistentFlags()` would result in a segfault
  - tried to use `AddFlagSet` to add it in `server.go` and that crashed hard. It crashes without the `AddFlagSet`, just the `Parent().PersistentFlags()` causes it
  - ```
    server: panic: runtime error: invalid memory address or nil pointer dereference
    server: [signal SIGSEGV: segmentation violation code=0x1 addr=0x188 pc=0xa3d692]
    server:
    server: goroutine 1 [running]:
    server: github.com/spf13/cobra.(*Command).PersistentFlags(0xc000169b00?)
    server:         /home/vscode/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1676 +0x12
    server: github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewServerCommand()
    server:         /home/vscode/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/server.go:240 +0xcda
    server: github.com/argoproj/argo-workflows/v3/cmd/argo/commands.NewCommand()
    server:         /home/vscode/go/src/github.com/argoproj/argo-workflows/cmd/argo/commands/root.go:100 +0x23e
    server: main.main()
    server:         /home/vscode/go/src/github.com/argoproj/argo-workflows/cmd/argo/main.go:14 +0x13
    2023/11/04 19:50:17 server: process exited 89278: exit status 2
    2023/11/04 19:50:17 server: context cancelled, stopping process
    server: exit status 2
    ```

- so instead of hacking together some logic here, I just added `viper` to `root.go`, where it does capture the env vars from subcommands too
  - tested by changing [this init log line](https://github.com/argoproj/argo-workflows/blob/a47e46208cd0029ef2e35019207d0b1ee4f85ea4/server/apiserver/argoserver.go#L272) to a `Debugf` instead of an `Infof` and then changing the `ARGO_LOGLEVEL` in the kit `tasks.yaml` to `DEBUG` as well
    - and then checking for this in the logs: `server: time="2023-11-04T20:12:56.151Z" level=debug msg="Argo Server started successfully on http://localhost:2746" url="http://localhost:2746"`
  - one caveat is that now env vars can be used for `loglevel`, `gloglevel`, and `verbose` for _all_ of the Argo CLI
    - nbd, IMO, but it is noteworthy to mention as a side-effect

Signed-off-by: Anton Gilgur <agilgur5@gmail.com>