test: deduplicate test manifests and fix "stress" profile
This deduplicates the test manifests using [Kustomize
Components](https://kubectl.docs.kubernetes.io/guides/config_management/components/)
and fixes the "stress" profile, which it seems has been broken ever
since `87cb1559107ec88dd418229b38113d70ba2a8580`. Running `make install
PROFILE=stress` on the `main` branch gives this error:
```
error: accumulating resources: accumulation err='merging resources from 'workflow-controller-podpriorityclass.yaml': may not add resource with an already registered id: PriorityClass.v1.scheduling.k8s.io/workflow-controller.[noNs]': must build at directory: '/home/vscode/go/src/github.com/argoproj/argo-workflows/test/e2e/manifests/stress/workflow-controller-podpriorityclass.yaml': file is not directory
```

I also used a component to handle scaling
`deploy/workflow-controller`/`deploy/argo-server` so we can remove those
lines from `Makefile`.

I used the following script to verify nothing unexpected changed:
```
set -e
for PROFILE in events minimal mysql plugins postgres prometheus sso; do
  echo "diffing $PROFILE"
  git checkout --quiet main
  kubectl kustomize --load-restrictor=LoadRestrictionsNone test/e2e/manifests/$PROFILE > "old_$PROFILE.yaml"
  git checkout --quiet deduplicate-manifest
  kubectl kustomize --load-restrictor=LoadRestrictionsNone test/e2e/manifests/$PROFILE > "new_$PROFILE.yaml"
  diff -U3 "old_$PROFILE.yaml" "new_$PROFILE.yaml" || true
done
```

Output:
```
diffing events
--- old_events.yaml	2024-12-16 03:45:49.404387813 +0000
+++ new_events.yaml	2024-12-16 03:45:49.650400191 +0000
@@ -3760,6 +3760,17 @@
 apiVersion: v1
 kind: Secret
 metadata:
+  annotations:
+    kubernetes.io/service-account.name: argo-server
+  labels:
+    app.kubernetes.io/part-of: argo
+  name: argo-server.service-account-token
+  namespace: argo
+type: kubernetes.io/service-account-token
+---
+apiVersion: v1
+kind: Secret
+metadata:
   labels:
     app.kubernetes.io/part-of: argo
   name: argo-workflows-webhook-clients
diffing minimal
diffing mysql
diffing plugins
diffing postgres
diffing prometheus
--- old_prometheus.yaml	2024-12-16 03:45:52.009518890 +0000
+++ new_prometheus.yaml	2024-12-16 03:45:52.203528651 +0000
@@ -3499,6 +3499,16 @@
 apiVersion: v1
 kind: Secret
 metadata:
+  annotations:
+    kubernetes.io/service-account.name: argo-server
+  labels:
+    app.kubernetes.io/part-of: argo
+  name: argo-server.service-account-token
+type: kubernetes.io/service-account-token
+---
+apiVersion: v1
+kind: Secret
+metadata:
   labels:
     app.kubernetes.io/part-of: argo
   name: argo-workflows-webhook-clients
@@ -3728,7 +3738,6 @@
   name: argo-server
   namespace: argo
 spec:
-  replicas: 0
   selector:
     matchLabels:
       app: argo-server
@@ -3785,7 +3794,6 @@
   name: workflow-controller
   namespace: argo
 spec:
-  replicas: 0
   selector:
     matchLabels:
       app: workflow-controller
diffing sso
```

Signed-off-by: Mason Malone <651224+MasonM@users.noreply.github.com>