ci: follow-up changes and fix flaky Windows tests. Fixes #12744
This addresses the comments from
https://github.com/argoproj/argo-workflows/pull/13660. Also, it
hopefully fixes the flaky `CI / Windows Unit Tests (pull_request)` test
suite. The errors indicate it's trying to write temp files to `/tmp`:
```
    --- FAIL: TestArtifactoryArtifactDriver_Load/Found (0.00s)
        http_test.go:75:
            	Error Trace:	D:/a/argo-workflows/argo-workflows/workflow/artifacts/http/http_test.go:75
            	Error:      	Received unexpected error:
            	            	open /tmp/found: The system cannot find the path specified.
            	Test:       	TestArtifactoryArtifactDriver_Load/Found
```

which obviously isn't the right directory under Windows, but the test
does pass sometimes, and it seems like writing to the wrong directory
would cause consistent failures. Regardless, the tests should be using
`os.CreateTemp()` for this anyway.

Signed-off-by: Mason Malone <mmalone@adobe.com>